export const DUMMY_DATA = [
  {
    id: 1,
    bgUrl:
      "https://lh3.googleusercontent.com/z_cgNJVf4f8WGOcmpRnZv0XNvxtEh-oozLHJvqJMOHqWUFZrHSerZezYvLS6VUF8DmrtAwj7nqynKVMdhJ-VvJbWAzdoijJnnlTH=h200",
    pfp: "https://lh3.googleusercontent.com/iXOXEXycCgZgBhc-Ry8s7k2x2TSG87Q0wqOM1l72dIUUh7wLF_d4K9SqWxRNjfcwDmjJPhoEeplHrMREyqYqndBvwtH-JsJc4rIJ4g=s100",
    username: "Monster",
    description: "Monster Ape Club is a collection of 7,999 unique generated 3D Monster Apes, stored on the Ethereum Blockchain. The art is made by N-Hance Studio. Their artists collaborated with Blizzard, Riot Games, and other famous projects.",
    category_id: 1,
    collectionname: "Monster Ape Club | MAC",
    slug: "monsterapeclub",
    item: 12,
    owner: 20,
    floorPrice: 2,
    traded: 1,
  },
  {
    id: 2,
    bgUrl:
      "https://lh3.googleusercontent.com/UbGuL01S-DZDVPaybBFlBT79hoD9tVtCSrQaYTYFCzkFnz5GB8Y1muAtGGYThaZpvoHkxncKDkLrtrXAiKid5OkD_WvFGGCc0v0psg=h200",
    pfp: "https://lh3.googleusercontent.com/UbGuL01S-DZDVPaybBFlBT79hoD9tVtCSrQaYTYFCzkFnz5GB8Y1muAtGGYThaZpvoHkxncKDkLrtrXAiKid5OkD_WvFGGCc0v0psg=h200",
    username: "Divine",
    description: "The Official Divine Anarchy Collection. 10,011 Children of Anarchy.",
    category_id: 2,
    collectionname: "Divine Anarchy",
    slug: "divinanarchy",
    item: '10K',
    owner: '40K',
    floorPrice: 2,
    traded: '2k',
  },
  {
    id: 3,
    bgUrl:
      "https://lh3.googleusercontent.com/FP_XvavrnD4c75THPr-dHfnTd4iNkboatdtCZfroGN__p7IQvgCapHtclES999mBmThzeU6Qlr5z6FS2TgUnfPITkjlcv83syX0X=h200",
    pfp: "https://lh3.googleusercontent.com/XvTK5ub2lJfUIDC4YaqySUDFKP3DVECUua876s2VLHNCmwaSZf35sY2JINaWVobWxLSbqhIOLX0vTl5jxuRPS2SbhnZSA7O-5iyIL0w=s100",
    username: "Bedlam-deployer",
    description: "Mecha Chaotic is an experiment in decentralized game theory and emergent phenomena. Your journey into the Mecha Chaotic Metaverse begins with an interactive minting ritual where the decisions you and the community make decide the rarity of each Mecha",
    category_id: 3,
    collectionname: "Mecha Chaotic: Bedlam",
    slug: "mechachaotic",
    item: 127,
    owner: 50,
    floorPrice: 21,
    traded: 10,
  },
  {
    id: 4,
    bgUrl:
      "https://lh3.googleusercontent.com/_ftGYT7QRHP-KzuNBOSDiWjtWkfrVR8yGP_nPnHELybXmd8b6PZqUP0oNRS0T2IbQYQBAgDYeA1fckfI7ZW7KWOscXmc7S2dEXmLX18=h200",
    pfp: "https://lh3.googleusercontent.com/_ftGYT7QRHP-KzuNBOSDiWjtWkfrVR8yGP_nPnHELybXmd8b6PZqUP0oNRS0T2IbQYQBAgDYeA1fckfI7ZW7KWOscXmc7S2dEXmLX18=h200",
    username: "danielnorkin",
    description:
      "After making instrumentals / beats for over 20 years, I want to release them as NFTs instead of other digital platforms. All music NFTs include un-lockable content that includes a 24 bit Mastered WAV file and full song stems.",
    category_id: 4,
    collectionname: "Instrumentals / Beats",
    slug: "instrumentals-beats",
    item: 10,
    owner: 3,
    floorPrice: 0.3,
    traded: 1,
  },
  {
    id: 5,
    bgUrl:
      "https://lh3.googleusercontent.com/Kw1hzrfNpj4jK34MpfPz_wMpajw412nAGRQY9_-a1wxg1Q0AC-php9C8wOHodmLe86d0vTn6FGFJybu-4Ovb5H10cc7qJlExS_mQ=h200",
    pfp: "https://lh3.googleusercontent.com/Kw1hzrfNpj4jK34MpfPz_wMpajw412nAGRQY9_-a1wxg1Q0AC-php9C8wOHodmLe86d0vTn6FGFJybu-4Ovb5H10cc7qJlExS_mQ=h200",
    username: "Tylersjourney",
    description: "Sleepless Streets is a Sci-fi/Cyberpunk 75 image collection that takes my signature vibrant photography style from the sold-out Toronto Iconscollection to the streets. This is all part of my 6 year journey battling a brain tumor and overcoming it all while chasing my dreams and capturing stories in the streets that I hope outlive me. Every image I create is inspired by my endless dreams I've experienced over the years. Chasing adverse weather and utilizing how colour reflects off the rain I've found showcases these rare street moments the best.Each image I create is truly unique to my experience of the city late at night, I hope that each image you collect connects with you the same way they connected with me when I captured them.",
    category_id: 5,
    collectionname: "Sleepless Streets",
    slug: "sleeplessstreets",
    item: 75,
    owner: 50,
    floorPrice: 0.85,
    traded: 34.2,
  },
  {
    id: 6,
    bgUrl:
      "https://lh3.googleusercontent.com/gzhe3ktKW5ZQ8S0FHzDRvE4UwwOQm9YGCiac59kMsL7IdVZif5GRU0lTXF9YQGClHpqpVU8HckVZXemgZ3hf6Ob0jcK3qFhSEmbeaA=h200",
    pfp: "https://lh3.googleusercontent.com/dDAOgeM0TdoTfPUsiU8C7K7NgK4A-34qxuAkLKGyd_pm1_nk6guUfBzEnDz995eT_KsiXeBcIG7rBT08u-DJ5fMVldss7I_8mGvGPws=s100",
    username: "RobGronkowski",
    description:
      "The Rob Gronkowski Championship Series NFT Collection commemorates GRONKs four historic Championships with five limited edition NFT trading cards. Each card is a unique piece of memorabilia digitally hand signed and numbered by GRONK. Collect all four cards to complete the full Rob Gronkowski Championship Series NFT set! The crown jewel of the drop will be a rare 1-of-1 Rob Gronkowski Career Highlight Refractor Card, which includes a meet and greet with GRONK and tickets to one of his games next season.",
    category_id: 6,
    collectionname: "Rob Gronkowski Championship Series NFTs",
    slug: "robgronkowski",
    item: 349,
    owner: 103,
    floorPrice: 1.98,
    traded: 1.2,
  },
];